version: "3"
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: ql
    restart: unless-stopped
    tty: true
    ports:
      - 9001:5700
      - 9011:5701
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    volumes:
      - ./config:/ql/config
      - ./log:/ql/log
      - ./db:/ql/db
      - ./repo:/ql/repo
      - ./raw:/ql/raw
      - ./scripts:/ql/scripts
      - ./jbot:/ql/jbot
      - ./ninja:/ql/ninja