version: "2.0"
services:
  jd:
    image: nevinee/jd:v4     # 不使用bot则为nevinee/jd:v4
    container_name: jd
    restart: always
    tty: true
    network_mode: bridge
    hostname: jd
    volumes:
      - ./config:/jd/config
      - ./log:/jd/log
      - ./own:/jd/own
    environment: 
      - ENABLE_HANGUP=false  # 是否启用挂机
      - ENABLE_TG_BOT=false  # 是否启用TG BOT，v4-bot标签特有的，v4标签没有